# Generated by Django 2.2.24 on 2021-12-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование товара', max_length=200)),
                ('height', models.FloatField(help_text='Ширина')),
                ('length', models.FloatField(help_text='Длинна/диаметр')),
            ],
        ),
    ]
